module.exports = [{
        "Image": "https://i.gadgets360cdn.com/products/large/1549533234_635_New_Nintendo_2DS_XL.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "New Nintendo 2DS XL (Black/Turquoise)",
        "Model": "New 2DS XL",
        "Price": "₹ 27,999",
        "Total Ratings": "755",
        "1 Stars": 9,
        "2 Stars": 4,
        "3 Stars": 3,
        "4 Stars": 10,
        "5 Stars": 74,
        "about": "01-06-2017| Wi-fi Yes| HDMI - No"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549532799_635_new_nintendo_3ds_xl.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "New Nintendo 3DS XL Monster Hunter (Blue)",
        "Model": "New 3DS XL",
        "Price": "₹ 19,990",
        "Total Ratings": "237",
        "1 Stars": 8,
        "2 Stars": 4,
        "3 Stars": 4,
        "4 Stars": 10,
        "5 Stars": 74,
        "about": "01-02-2015| Wi-fi Yes| HDMI - No"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549529354_635_nintendo_3ds.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "Nintendo 3DS (Black)",
        "Model": "3DS",
        "Price": "₹ 60,000",
        "Total Ratings": "386",
        "1 Stars": 8,
        "2 Stars": 3,
        "3 Stars": 6,
        "4 Stars": 12,
        "5 Stars": 70,
        "about": "01-03-2011| Wi-fi Yes| HDMI - No"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549529354_635_nintendo_3ds.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "Nintendo 3DS (Midnight Purple)",
        "Model": "3DS",
        "Price": "₹ 42,330",
        "Total Ratings": "386",
        "1 Stars": 8,
        "2 Stars": 3,
        "3 Stars": 6,
        "4 Stars": 12,
        "5 Stars": 70,
        "about": "01-03-2011| Wi-fi Yes| HDMI - No"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549533234_635_New_Nintendo_2DS_XL.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "New Nintendo 2DS XL Pikachu Edition (Yellow)",
        "Model": "New 2DS XL",
        "Price": "₹ 30,075",
        "Total Ratings": "755",
        "1 Stars": 9,
        "2 Stars": 4,
        "3 Stars": 3,
        "4 Stars": 10,
        "5 Stars": 74,
        "about": "01-06-2017| Wi-fi Yes| HDMI - No"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549533234_635_New_Nintendo_2DS_XL.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "New Nintendo 2DS XL (White/Orange)",
        "Model": "New 2DS XL",
        "Price": "₹ 21,990",
        "Total Ratings": "755",
        "1 Stars": 9,
        "2 Stars": 4,
        "3 Stars": 3,
        "4 Stars": 10,
        "5 Stars": 74,
        "about": "01-06-2017| Wi-fi Yes| HDMI - No"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549526400_635_nintendo_switch_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "Nintendo Switch (Black)",
        "Model": "Switch",
        "Price": "₹ 31,739",
        "Total Ratings": "1,009",
        "1 Stars": 13,
        "2 Stars": 3,
        "3 Stars": 4,
        "4 Stars": 8,
        "5 Stars": 72,
        "about": "01-03-2017| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549528045_635_nintendo_wii_u_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "Nintendo Wii U",
        "Model": "Wii U",
        "Price": "₹ 107,441",
        "Total Ratings": "168",
        "1 Stars": 3,
        "2 Stars": 2,
        "3 Stars": 1,
        "4 Stars": 10,
        "5 Stars": 84,
        "about": "01-11-2012| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549462346_635_ps4_slim_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony PlayStation 4 (Black, 500GB)",
        "Model": "PlayStation 4",
        "Price": "₹ 30,990",
        "Total Ratings": "2,020",
        "1 Stars": 7,
        "2 Stars": 2,
        "3 Stars": 4,
        "4 Stars": 12,
        "5 Stars": 75,
        "about": "01-11-2013| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549462346_635_ps4_slim_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony PlayStation 4 (Silver, 500GB)",
        "Model": "PlayStation 4",
        "Price": "₹ 44,990",
        "Total Ratings": "2,020",
        "1 Stars": 7,
        "2 Stars": 2,
        "3 Stars": 4,
        "4 Stars": 12,
        "5 Stars": 75,
        "about": "01-11-2013| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549457624_635_xbox_one_s.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox One S (White, 1TB)",
        "Model": "Xbox One S",
        "Price": "₹ 30,990",
        "Total Ratings": "405",
        "1 Stars": 3,
        "2 Stars": 2,
        "3 Stars": 3,
        "4 Stars": 15,
        "5 Stars": 77,
        "about": "01-08-2016| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549457342_635_ps4_pro_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony Playstation 4 Pro (White)",
        "Model": "PlayStation 4 Pro",
        "Price": "₹ 42,500",
        "Total Ratings": "607",
        "1 Stars": 11,
        "2 Stars": 2,
        "3 Stars": 4,
        "4 Stars": 10,
        "5 Stars": 72,
        "about": "01-11-2016| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549457342_635_ps4_pro_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony Playstation 4 Pro (Black, 1TB)",
        "Model": "PlayStation 4 Pro",
        "Price": "₹ 36,594",
        "Total Ratings": "607",
        "1 Stars": 11,
        "2 Stars": 2,
        "3 Stars": 4,
        "4 Stars": 10,
        "5 Stars": 72,
        "about": "01-11-2016| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549457342_635_ps4_pro_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony Playstation 4 Pro (Black)",
        "Model": "PlayStation 4 Pro",
        "Price": "₹ 31,500",
        "Total Ratings": "607",
        "1 Stars": 11,
        "2 Stars": 2,
        "3 Stars": 4,
        "4 Stars": 10,
        "5 Stars": 72,
        "about": "01-11-2016| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549531497_635_xbox_360_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox 360 (Black, 4GB)",
        "Model": "Xbox 360",
        "Price": "₹ 27,990",
        "Total Ratings": "412",
        "1 Stars": 8,
        "2 Stars": 1,
        "3 Stars": 6,
        "4 Stars": 13,
        "5 Stars": 72,
        "about": "01-11-2005| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549529231_635_ps3_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony Playstation 3 (Black)",
        "Model": "PlayStation 3",
        "Price": "₹ 13,900",
        "Total Ratings": "258",
        "1 Stars": 13,
        "2 Stars": 3,
        "3 Stars": 7,
        "4 Stars": 17,
        "5 Stars": 60,
        "about": "01-11-2006| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549529231_635_ps3_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony Playstation 3 (Black, 500GB)",
        "Model": "PlayStation 3",
        "Price": "₹ 22,500",
        "Total Ratings": "258",
        "1 Stars": 13,
        "2 Stars": 3,
        "3 Stars": 7,
        "4 Stars": 17,
        "5 Stars": 60,
        "about": "01-11-2006| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549457475_635_xbox_one_x.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox One X (Black, 1TB)",
        "Model": "Xbox One X",
        "Price": "₹ 43,990",
        "Total Ratings": "297",
        "1 Stars": 14,
        "2 Stars": 3,
        "3 Stars": 5,
        "4 Stars": 12,
        "5 Stars": 66,
        "about": "01-11-2017| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549457475_635_xbox_one_x.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox One X (Grey, 1TB)",
        "Model": "Xbox One X",
        "Price": "₹ 47,304",
        "Total Ratings": "297",
        "1 Stars": 14,
        "2 Stars": 3,
        "3 Stars": 5,
        "4 Stars": 12,
        "5 Stars": 66,
        "about": "01-11-2017| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1549457624_635_xbox_one_s.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox One S (Gradient Purple, 1TB)",
        "Model": "Xbox One S",
        "Price": "₹ 29,999",
        "Total Ratings": "405",
        "1 Stars": 3,
        "2 Stars": 2,
        "3 Stars": 3,
        "4 Stars": 15,
        "5 Stars": 77,
        "about": "01-08-2016| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1550244612_635_PS_VITA_OLED.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony Playstation Vita (Black)",
        "Model": "PlayStation Vita",
        "Price": "₹ 18,000",
        "Total Ratings": "19",
        "1 Stars": 16,
        "2 Stars": 0,
        "3 Stars": 0,
        "4 Stars": 16,
        "5 Stars": 68,
        "about": "01-02-2012| Wi-fi Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1550244612_635_PS_VITA_OLED.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sony",
        "ProductName": "Sony Playstation Vita (Gold)",
        "Model": "PlayStation Vita",
        "Price": "₹ 16,800",
        "Total Ratings": "19",
        "1 Stars": 16,
        "2 Stars": 0,
        "3 Stars": 0,
        "4 Stars": 16,
        "5 Stars": 68,
        "about": "01-02-2012| Wi-fi Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1550061163_635_gameboy_advance_nintendo.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "",
        "Model": "Game Boy Advance",
        "Price": "",
        "Total Ratings": "",
        "1 Stars": 0,
        "2 Stars": 0,
        "3 Stars": 0,
        "4 Stars": 0,
        "5 Stars": 0,
        "about": "01-06-2001| Wi-fi Yes| HDMI - No"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1555479830_635_xbox_one_s_all_digital_edition.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox One S (White, 1TB)",
        "Model": "Xbox One S All-Digital Edition",
        "Price": "₹ 19,990",
        "Total Ratings": "463",
        "1 Stars": 18,
        "2 Stars": 4,
        "3 Stars": 5,
        "4 Stars": 11,
        "5 Stars": 62,
        "about": "01-05-2019| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1550242035_635_NES_CLASSIC.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nintendo",
        "ProductName": "",
        "Model": "NES Classic Edition",
        "Price": "",
        "Total Ratings": "",
        "1 Stars": 0,
        "2 Stars": 0,
        "3 Stars": 0,
        "4 Stars": 0,
        "5 Stars": 0,
        "about": "01-11-2016| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1555479830_635_xbox_one_s_all_digital_edition.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox One S (Black)",
        "Model": "Xbox One S All-Digital Edition",
        "Price": "₹ 21,990",
        "Total Ratings": "463",
        "1 Stars": 18,
        "2 Stars": 4,
        "3 Stars": 5,
        "4 Stars": 11,
        "5 Stars": 62,
        "about": "01-05-2019| Wi-fi Yes| HDMI - Yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/1555479830_635_xbox_one_s_all_digital_edition.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Microsoft",
        "ProductName": "Microsoft Xbox One S (White)",
        "Model": "Xbox One S All-Digital Edition",
        "Price": "₹ 21,490",
        "Total Ratings": "463",
        "1 Stars": 18,
        "2 Stars": 4,
        "3 Stars": 5,
        "4 Stars": 11,
        "5 Stars": 62,
        "about": "01-05-2019| Wi-fi Yes| HDMI - Yes"
    }
];