module.exports = [{
        "Brand": "Vivo",
        "Product Name": "Vivo V11 Pro (6GB RAM, 64GB) - Supernova Red",
        "Model": "V11 Pro",
        "Image": "https://i.gadgets360cdn.com/products/large/1536222480_635_vivo_v11_pro.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 5,
        "2 Stars": 2,
        "3 Stars": 6,
        "4 Stars": 18,
        "5 Stars": 70,
        "TotalRating": 6534,
        "Price": "₹ 28,990",
        "RAM": "RAM-6GB",
        "Launched": "Lauched 01-09-2018 |",
        "Colours": "Dazzling Gold, Starry Black",
        "About": "Lauched 01-09-2018 |Dazzling Gold, Starry Black"
    },
    {
        "Brand": "Xiaomi",
        "Product Name": "Xiaomi Redmi 6A (32GB) - Blue",
        "Model": "Redmi 6A",
        "Image": "https://i.gadgets360cdn.com/products/large/1528791254_635_xiaoim_redmi_6a.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 8,
        "2 Stars": 3,
        "3 Stars": 9,
        "4 Stars": 26,
        "5 Stars": 55,
        "TotalRating": 29624,
        "Price": "₹ 6,450",
        "RAM": "RAM-2GB",
        "Launched": " Launched 01-06-2018 |",
        "Colours": "Black, Blue, Gold, Rose Gold |",
        "About": " Launched 01-06-2018 |Black, Blue, Gold, Rose Gold |RAM-2GB"
    },
    {
        "Brand": "Realme",
        "Product Name": "Realme 3 Pro (6GB RAM, 128GB) - Nitro Blue",
        "Model": "3 Pro",
        "Image": "https://i.gadgets360cdn.com/products/large/1555920099_635_realme3_pro_db.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 3,
        "2 Stars": 1,
        "3 Stars": 5,
        "4 Stars": 21,
        "5 Stars": 70,
        "TotalRating": 47902,
        "Price": "₹ 16,999",
        "RAM": "| RAM-4GB",
        "Launched": "Launched 01-04-2019",
        "Colours": "| colours -Carbon Grey, Lightning Purple, Nitro Blue",
        "About": "Launched 01-04-2019| colours -Carbon Grey, Lightning Purple, Nitro Blue| RAM-4GB"
    },
    {
        "Brand": "Lava",
        "Product Name": "Lava Flair P1 (256MB RAM, 2GB) - Black",
        "Model": "Flair P1",
        "Image": "https://cdn.gadgets360.com/content/assets/products/lava-flair-p1-2667_480X960_1433497583.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 29,
        "2 Stars": 7,
        "3 Stars": 6,
        "4 Stars": 54,
        "5 Stars": 4,
        "TotalRating": 69,
        "Price": "₹ 1,899",
        "RAM": "| RAM-256MB",
        "Launched": "Launched 01-05-2015",
        "Colours": "| colours -Black, White",
        "About": "Launched 01-05-2015| colours -Black, White| RAM-256MB"
    },
    {
        "Brand": "Micromax",
        "Product Name": "Micromax Canvas Selfie Lens (8GB) - Grey",
        "Model": "Canvas Selfie Lens",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/623201533654PM_635_micromax_canvas_selfie_lens.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 16,
        "2 Stars": 0,
        "3 Stars": 8,
        "4 Stars": 26,
        "5 Stars": 51,
        "TotalRating": 89,
        "Price": "₹ 8,000",
        "RAM": "| RAM-1GB",
        "Launched": "Launched 01-06-2015",
        "Colours": "| colours -White Champagne, Moondust Grey",
        "About": "Launched 01-06-2015| colours -White Champagne, Moondust Grey| RAM-1GB"
    },
    {
        "Brand": "Karbonn",
        "Product Name": "Karbonn Karbonn Smart A5 Star (256MB RAM, 104MB) - Black",
        "Model": "Smart A5 Star",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/7292013122523PM_635_karbonn_smart_a5_star.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 86,
        "2 Stars": 14,
        "3 Stars": 0,
        "4 Stars": 0,
        "5 Stars": 0,
        "TotalRating": 7,
        "Price": "₹ 4,299",
        "RAM": "| RAM-256MB",
        "Launched": "Launched 01-07-2013",
        "Colours": "| colours -Black",
        "About": "Launched 01-07-2013| colours -Black| RAM-256MB"
    },
    {
        "Brand": "Intex",
        "Product Name": "Intex Aqua Power M (1GB RAM, 8GB) - Champagne",
        "Model": "Aqua Power M",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/1112016105825AM_635_Intex_Aqua_power_m.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 34,
        "2 Stars": 10,
        "3 Stars": 10,
        "4 Stars": 10,
        "5 Stars": 34,
        "TotalRating": 67,
        "Price": "₹ 3,499",
        "RAM": "| RAM-1GB",
        "Launched": "Launched 01-11-2016",
        "Colours": "| colours -Champagne Gold`",
        "About": "Launched 01-11-2016| colours -Champagne Gold`| RAM-1GB"
    },
    {
        "Brand": "Lava",
        "Product Name": "Lava A32 (256MB RAM, 512MB) - White",
        "Model": "A32",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/7202016123002PM_635_lava_a32.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 43,
        "2 Stars": 7,
        "3 Stars": 14,
        "4 Stars": 10,
        "5 Stars": 26,
        "TotalRating": 42,
        "Price": "₹ 1,999",
        "RAM": "| RAM-256MB",
        "Launched": "Launched 01-07-2016",
        "Colours": "| colours -Black, White",
        "About": "Launched 01-07-2016| colours -Black, White| RAM-256MB"
    },
    {
        "Brand": "Vivo",
        "Product Name": "Vivo Z1x (6GB RAM, 128GB) - Fusion Blue",
        "Model": "Z1x",
        "Image": "https://i.gadgets360cdn.com/products/large/vivo-z1x-383x800-1567757092.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 4,
        "2 Stars": 2,
        "3 Stars": 5,
        "4 Stars": 21,
        "5 Stars": 68,
        "TotalRating": 20101,
        "Price": "₹ 17,990",
        "RAM": "| RAM-4GB",
        "Launched": "Launched 6th September 2019",
        "Colours": "| colours -Fusion Blue, Phantom Purple",
        "About": "Launched 6th September 2019| colours -Fusion Blue, Phantom Purple| RAM-4GB"
    },

    {
        "Brand": "Micromax",
        "Product Name": "Micromax Canvas Pace 4G (1GB RAM, 8GB) - Black",
        "Model": "Canvas Pace 4G",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/1127201530107PM_635_micromax_canvas_pace_4g.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 16,
        "2 Stars": 5,
        "3 Stars": 16,
        "4 Stars": 22,
        "5 Stars": 41,
        "TotalRating": 37,
        "Price": "₹ 7,499",
        "RAM": "| RAM-1GB",
        "Launched": "Launched 01-11-2015",
        "Colours": "| colours -Black",
        "About": "Launched 01-11-2015| colours -Black| RAM-1GB"
    },
    {
        "Brand": "10.or",
        "Product Name": "10.or E (3GB RAM, 32GB) - Beyond Black",
        "Model": "E",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/96201753308PM_635_10_or_e.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 19,
        "2 Stars": 5,
        "3 Stars": 11,
        "4 Stars": 25,
        "5 Stars": 40,
        "TotalRating": 4533,
        "Price": "₹ 5,999",
        "RAM": "| RAM-2GB",
        "Launched": "Launched 01-09-2017",
        "Colours": "| colours -Aim Gold, Beyond Black",
        "About": "Launched 01-09-2017| colours -Aim Gold, Beyond Black| RAM-2GB"
    },
    {
        "Brand": "Google",
        "Product Name": "Google Pixel 3a XL (4GB RAM, 64GB) - Just Black",
        "Model": "Pixel 3a XL",
        "Image": "https://i.gadgets360cdn.com/products/large/1557253966_635_Google_Pixel_3a_xl_DB.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 8,
        "2 Stars": 2,
        "3 Stars": 5,
        "4 Stars": 16,
        "5 Stars": 69,
        "TotalRating": 165,
        "Price": "₹ 34,999",
        "RAM": "| RAM-4GB",
        "Launched": "Launched 7th May 2019",
        "Colours": "| colours -Just Black, Clearly White",
        "About": "Launched 7th May 2019| colours -Just Black, Clearly White| RAM-4GB"
    },
    {
        "Brand": "Samsung",
        "Product Name": "Samsung Galaxy A9 (2018) (6GB RAM, 128GB) - Lemonade Blue",
        "Model": "Galaxy A9 (2018)",
        "Image": "https://i.gadgets360cdn.com/products/large/1539250545_635_samsung_galaxy_a9_2018.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 15,
        "2 Stars": 6,
        "3 Stars": 8,
        "4 Stars": 20,
        "5 Stars": 50,
        "TotalRating": 382,
        "Price": "₹ 23,900",
        "RAM": "| RAM-6GB",
        "Launched": "Launched 01-10-2018",
        "Colours": "| colours -Bubble Gum Pink, Bubblegum Pink, Caviar Black",
        "About": "Launched 01-10-2018| colours -Bubble Gum Pink, Bubblegum Pink, Caviar Black| RAM-6GB"
    },
    {
        "Brand": "Intex",
        "Product Name": "Intex Aqua Q3 (1GB RAM, 8GB) - Blue",
        "Model": "Aqua Q3",
        "Image": "https://cdn.gadgets360.com/content/assets/products/intex-aqua-q3-2378_480X960_1438858157.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 67,
        "2 Stars": 17,
        "3 Stars": 0,
        "4 Stars": 17,
        "5 Stars": 0,
        "TotalRating": 6,
        "Price": "₹ 5,330",
        "RAM": "| RAM-1GB",
        "Launched": "Launched 01-02-2015",
        "Colours": "| colours -White",
        "About": "Launched 01-02-2015| colours -White| RAM-1GB"
    },
    {
        "Brand": "BlackBerry",
        "Product Name": "BlackBerry Bold 9900 (768MB RAM, 8GB) - White",
        "Model": "Bold 9900",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/5312013103000AM_635_Blackberry_Bold_9900.png?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 58,
        "2 Stars": 11,
        "3 Stars": 8,
        "4 Stars": 5,
        "5 Stars": 20,
        "TotalRating": 66,
        "Price": "₹ 8,500",
        "RAM": "| RAM-768MB",
        "Launched": "Launched 01-08-2011",
        "Colours": "| colours -Black",
        "About": "Launched 01-08-2011| colours -Black| RAM-768MB"
    },
    {
        "Brand": "Vivo",
        "Product Name": "Vivo Z1x (6GB RAM, 64GB) - Fusion Blue",
        "Model": "Z1x",
        "Image": "https://i.gadgets360cdn.com/products/large/vivo-z1x-383x800-1567757092.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 4,
        "2 Stars": 2,
        "3 Stars": 5,
        "4 Stars": 21,
        "5 Stars": 68,
        "TotalRating": 20101,
        "Price": "₹ 16,990",
        "RAM": "| RAM-4GB",
        "Launched": "6th September 2019",
        "Colours": "| colours -Fusion Blue, Phantom Purple",
        "About": "6th September 2019| colours -Fusion Blue, Phantom Purple| RAM-4GB"
    },
    {
        "Brand": "Panasonic",
        "Product Name": "Panasonic P77 (16GB) - White",
        "Model": "P77",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/922201622850PM_635_panasonic_p_77.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 43,
        "2 Stars": 6,
        "3 Stars": 11,
        "4 Stars": 11,
        "5 Stars": 28,
        "TotalRating": 53,
        "Price": "₹ 4,870",
        "RAM": "| RAM-1GB",
        "Launched": "Launched 01-09-2016",
        "Colours": "| colours -Grey, White",
        "About": "Launched 01-09-2016"
    },
    {
        "Brand": "Swipe",
        "Product Name": "Swipe Konnect Power (2GB RAM, 16GB) - Gold",
        "Model": "Konnect Power",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/84201740858PM_635_swipe_konnect_power.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 26,
        "2 Stars": 7,
        "3 Stars": 16,
        "4 Stars": 15,
        "5 Stars": 36,
        "TotalRating": 301,
        "Price": "₹ 3,599",
        "RAM": "| RAM-2GB",
        "Launched": "Launched 01-08-2017",
        "Colours": "",
        "About": ""
    },
    {
        "Brand": "Samsung",
        "Product Name": "Samsung Galaxy Note 5 (64GB) - Black Sapphire",
        "Model": "Galaxy Note 5",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/samsung_galaxy_note_5_2_2866_480X960_922201524126PM.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 19,
        "2 Stars": 5,
        "3 Stars": 4,
        "4 Stars": 14,
        "5 Stars": 58,
        "TotalRating": 345,
        "Price": "₹ 20,099",
        "RAM": "| RAM-4GB",
        "Launched": "Launched 01-08-2015",
        "Colours": "| colours -Black Sapphire, Gold Platinum, Silver Titanium",
        "About": ""
    },
    {
        "Brand": "BlackBerry",
        "Product Name": "BlackBerry Curve 9360 (512MB RAM, 512MB) - Black",
        "Model": "Curve 9360",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/5312013103320AM_635_BlackBerry_Curve_9360.png?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 62,
        "2 Stars": 6,
        "3 Stars": 4,
        "4 Stars": 10,
        "5 Stars": 18,
        "TotalRating": 138,
        "Price": "₹ 4,299",
        "RAM": "| RAM-512MB",
        "Launched": "Launched 01-08-2011",
        "Colours": "| colours -Black, White",
        "About": ""
    },
    {
        "Brand": "Panasonic",
        "Product Name": "Panasonic P99 (2GB RAM, 16GB) - Black",
        "Model": "P99",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/928201755449PM_635_panasonic_p99_db.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 33,
        "2 Stars": 9,
        "3 Stars": 13,
        "4 Stars": 13,
        "5 Stars": 32,
        "TotalRating": 408,
        "Price": "₹ 5,499",
        "RAM": "| RAM-2GB",
        "Launched": "Launched 01-09-2017",
        "Colours": "| colours -Champagne Gold, Black, Blue",
        "About": ""
    },
    {
        "Brand": "Spice",
        "Product Name": "Spice XLife 431q Lite (512MB RAM, 4GB) - Grey",
        "Model": "XLife 431q Lite",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/624201545250PM_635_spice_xlife_431q_lite.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 33,
        "2 Stars": 0,
        "3 Stars": 11,
        "4 Stars": 17,
        "5 Stars": 39,
        "TotalRating": 18,
        "Price": "₹ 3,236",
        "RAM": "| RAM-512MB",
        "Launched": "Launched 01-06-2015",
        "Colours": "",
        "About": ""
    },
    {
        "Brand": "HTC",
        "Product Name": "HTC One (E8) (2GB RAM, 16GB) - Drak Grey",
        "Model": "One (E8)",
        "Image": "https://drop.ndtv.com/TECH/product_database/images/711201410353PM_635_htc_one_e8_single_sim.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 12,
        "2 Stars": 2,
        "3 Stars": 5,
        "4 Stars": 15,
        "5 Stars": 66,
        "TotalRating": 107,
        "Price": "₹ 17,999",
        "RAM": "| RAM-2GB",
        "Launched": "Launched 01-05-2014",
        "Colours": "| colours -Polar White, Electric Crimson, Maldives Blue, Misty Gray",
        "About": ""
    },
    {
        "Brand": "Smartron",
        "Product Name": "Smartron t.phone P (3GB RAM, 32GB) - Black",
        "Model": "t.phone P",
        "Image": "https://i.gadgets360cdn.com/products/large/1515655993_635_smartron_t_phone_p.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 15,
        "2 Stars": 7,
        "3 Stars": 12,
        "4 Stars": 24,
        "5 Stars": 42,
        "TotalRating": 906,
        "Price": "₹ 10,500",
        "RAM": "| RAM-3GB",
        "Launched": "Launched 01-01-2018",
        "Colours": "| colours -Black",
        "About": ""
    },
    {
        "Brand": "Motorola",
        "Product Name": "Motorola Moto G7 (4GB RAM, 64GB) - Ceramic Black",
        "Model": "Moto G7",
        "Image": "https://i.gadgets360cdn.com/products/large/1548317852_635_moto_g7.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "1 Stars": 14,
        "2 Stars": 4,
        "3 Stars": 8,
        "4 Stars": 23,
        "5 Stars": 52,
        "TotalRating": 541,
        "Price": "₹ 9,999",
        "RAM": "| RAM-4GB",
        "Launched": "Launched 01-02-2019",
        "Colours": "| colours -Ceramic Black, Ceramic White",
        "About": ""
    }
];