module.exports = [{
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548154943_832_vu_75-inch-led-ultra-hd-4k-tv-vu-s-oauhd75.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Vu",
        "Product Name": "Vu 75 Inches Ultra HD (4K) LED Smart TV (VU/S/OAUHD75)",
        "Model": "75 Inch LED Ultra HD (4K) TV (VU/S/OAUHD75)",
        "Model Name": "VU/S/OAUHD75",
        "Price": "â‚¹ 108,000",
        "TotalRating": 35,
        "1 Stars": 9,
        "2 Stars": 3,
        "3 Stars": 6,
        "4 Stars": 17,
        "5 Stars": 66,
        "TotalRating": 0,
        "About": "Black| Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153508_832_micromax_50-inch-led-full-hd-tv-50-canvas-3.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Micromax",
        "Product Name": "Micromax 50 Inches Full HD LED Smart TV (50 CANVAS 3)",
        "Model": "50 Inch LED Full HD TV (50 CANVAS 3)",
        "Model Name": "50 CANVAS 3",
        "Price": "â‚¹ 27,499",
        "TotalRating": 106,
        "1 Stars": 10,
        "2 Stars": 4,
        "3 Stars": 8,
        "4 Stars": 18,
        "5 Stars": 59,

        "About": "Silver | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153579_832_iffalcon_55-inch-led-ultra-hd-4k-tv-55k2a.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "iFFalcon",
        "Product Name": "Iffalcon 55 Inches Ultra HD (4K) LED Smart TV (55K2A, Black)",
        "Model": "55 Inch LED Ultra HD (4K) TV (55K2A)",
        "Model Name": "55K2A",
        "Price": "â‚¹ 36,999",
        "TotalRating": 997,
        "1 Stars": 12,
        "2 Stars": 3,
        "3 Stars": 5,
        "4 Stars": 22,
        "5 Stars": 58,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/vu-55-oa-55-oa-v1-original-imafqfjrx7zze7ph-416x266-1587537613.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Vu",
        "Product Name": "Vu 55 Inches Ultra HD (4K) LED Smart TV (Premium 55-OA, Black)",
        "Model": "55 Inch LED Ultra HD (4K) TV (Premium 55-OA)",
        "Model Name": "55-OA",
        "Price": "â‚¹ 36,999",
        "TotalRating": 1027,
        "1 Stars": 7,
        "2 Stars": 3,
        "3 Stars": 7,
        "4 Stars": 23,
        "5 Stars": 61,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/micromax-55ta7000uhd-original-imaffg4pngvpvm4x-416x245-1588062193.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Micromax",
        "Product Name": "Micromax 49 Inches Ultra HD (4K) LED Smart TV (49TA7000UHD, Black)",
        "Model": "49 Inch LED Ultra HD (4K) TV (49TA7000UHD)",
        "Model Name": "49TA7000UHD",
        "Price": "â‚¹ 33,999",
        "TotalRating": 27,
        "1 Stars": 7,
        "2 Stars": 4,
        "3 Stars": 0,
        "4 Stars": 26,
        "5 Stars": 63,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/vu-86-inch-led-ultra-hd-4k-tv-pixelight-hdr-vu-c-pxuhd86-1311x800-1591796840.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Vu",
        "Product Name": "Vu 86 Inches Ultra HD (4K) LED Smart TV (Pixelight HDR VU/C/PXUHD86, Black)",
        "Model": "86 Inch LED Ultra HD (4K) TV (Pixelight HDR VU/C/PXUHD86)",
        "Model Name": "VU/C/PXUHD86",
        "Price": "â‚¹ 400,000",
        "TotalRating": 0,
        "1 Stars": 100,
        "2 Stars": 0,
        "3 Stars": 0,
        "4 Stars": 0,
        "5 Stars": 0,

        "About": "Black | Smart tv - no"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/micromax-40cam6sfhd-original-imafhyaa5tp96qsm-416x247-1584786663.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Micromax",
        "Product Name": "Micromax 40 Inches Full HD LED Smart TV (40CAM6SFHD, Black)",
        "Model": "40 Inch LED Full HD TV (40CAM6SFHD)",
        "Model Name": "40CAM6SFHD",
        "Price": "â‚¹ 18,999",
        "TotalRating": 800,
        "1 Stars": 8,
        "2 Stars": 3,
        "3 Stars": 8,
        "4 Stars": 23,
        "5 Stars": 59,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153102_832_cloudwalker_32-inch-led-hd-ready-tv-32sh04x.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "CloudWalker",
        "Product Name": "CloudWalker Cloud TV 80cm (32 inch) HD Ready LED Smart TV(32SH04X)",
        "Model": "32 Inch LED HD Ready TV (32SH04X)",
        "Model Name": "32SH04X",
        "Price": "â‚¹ 11,999",
        "TotalRating": 44,
        "1 Stars": 7,
        "2 Stars": 0,
        "3 Stars": 5,
        "4 Stars": 23,
        "5 Stars": 66,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/iffalcon-65k3a-original-imafm59fkg8njeau-416x313-1584526405.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "iFFalcon",
        "Product Name": "iFFalcon 65 Inches Ultra HD (4K) LED Smart Android TV (65K3A, Black)",
        "Model": "65-inch LED Ultra HD (4K) Smart Android TV (65K3A)",
        "Model Name": "65K3A",
        "Price": "â‚¹ 58,499",
        "TotalRating": 116,
        "1 Stars": 3,
        "2 Stars": 2,
        "3 Stars": 3,
        "4 Stars": 23,
        "5 Stars": 68,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/43-UH-416x272-1587367203.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Vu",
        "Product Name": "Vu 43 Inches Ultra HD (4K) LED Smart TV (Pixelight 43-UH, Black)",
        "Model": "43 Inch LED Ultra HD (4K) TV (Pixelight 43-UH)",
        "Model Name": "43-UH",
        "Price": "â‚¹ 22,999",
        "TotalRating": 18,
        "1 Stars": 11,
        "2 Stars": 6,
        "3 Stars": 6,
        "4 Stars": 28,
        "5 Stars": 50,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153367_832_cloudwalker_43-inch-led-full-hd-tv-43sf04x.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "CloudWalker",
        "Product Name": "CloudWalker Cloud TV 109cm (43 inch) Full HD LED Smart TV(43SF04X)",
        "Model": "43 Inch LED Full HD TV (43SF04X)",
        "Model Name": "43SF04X",
        "Price": "â‚¹ 19,499",
        "TotalRating": 22,
        "1 Stars": 9,
        "2 Stars": 0,
        "3 Stars": 9,
        "4 Stars": 55,
        "5 Stars": 27,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/motorola-65sauhdm-original-imafm59fztjjshhm-416x297-1584956541.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Motorola",
        "Product Name": "Motorola 50 Inches Ultra HD (4K) LED Smart TV (50SAUHDM, Black)",
        "Model": "50 Inch LED Ultra HD (4K) TV (50SAUHDM)",
        "Model Name": "50SAUHDM",
        "Price": "â‚¹ 34,999",
        "TotalRating": 1094,
        "1 Stars": 12,
        "2 Stars": 4,
        "3 Stars": 10,
        "4 Stars": 22,
        "5 Stars": 53,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/marq-by-flipkart-65sauhd-original-imafm59fn624etpf-416x267-1584786926.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "MarQ by Flipkart",
        "Product Name": "MarQ by Flipkart 65 Inches Ultra HD (4K) LED Smart TV (65SAUHD, Grey)",
        "Model": "65 Inch LED Ultra HD (4K) TV (65SAUHD)",
        "Model Name": "65SAUHD",
        "Price": "â‚¹ 64,999",
        "TotalRating": 91,
        "1 Stars": 7,
        "2 Stars": 2,
        "3 Stars": 5,
        "4 Stars": 21,
        "5 Stars": 65,

        "About": "Grey | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/motorola-65sauhdm-original-imafm59fztjjshhm-416x297-1585046699.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Motorola",
        "Product Name": "Motorola 75 Inches Ultra HD (4K) LED Smart TV (75SAUHDM, Black)",
        "Model": "75 Inch LED Ultra HD (4K) TV (75SAUHDM)",
        "Model Name": "75SAUHDM",
        "Price": "â‚¹ 119,999",
        "TotalRating": 15,
        "1 Stars": 40,
        "2 Stars": 0,
        "3 Stars": 0,
        "4 Stars": 0,
        "5 Stars": 60,

        "About": "Black | Smart tv - no"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/nokia-smart-tv-43-db-1200x675-1591247626.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nokia",
        "Product Name": "Nokia 43 Inches Ultra HD (4K) LED Smart Android TV (43CAUHDN, Black)",
        "Model": "43 Inch Ultra HD TV (4K)",
        "Model Name": "43CAUHDN",
        "Price": "â‚¹ 31,999",
        "TotalRating": 1066,
        "1 Stars": 9,
        "2 Stars": 3,
        "3 Stars": 7,
        "4 Stars": 23,
        "5 Stars": 58,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153766_832_blaupunkt_55-inch-led-ultra-hd-tv-bla55au680.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Blaupunkt",
        "Product Name": "Blaupunkt 55 Inches Ultra HD LED Smart TV (BLA55AU680)",
        "Model": "55 Inch LED Ultra HD TV (BLA55AU680)",
        "Model Name": "BLA55AU680",
        "Price": "â‚¹ 33,999",
        "TotalRating": 685,
        "1 Stars": 11,
        "2 Stars": 4,
        "3 Stars": 4,
        "4 Stars": 19,
        "5 Stars": 63,

        "About": "Black | Smart tv - no"
    },
    {
        "Image": "https://gadgets.ndtv.com/static/icons/tv-icon.png?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Sansui",
        "Product Name": "Sansui 40 Inches Full HD LED Smart TV (Pro View 40VAOFHDS / 40NVAOFHDS, Black)",
        "Model": "40 Inch LED Full HD TV (Pro View 40VAOFHDS / 40NVAOFHDS)",
        "Model Name": "40VAOFHDS / 40NVAOFHDS",
        "Price": "â‚¹ 16,499",
        "TotalRating": 1015,
        "1 Stars": 5,
        "2 Stars": 2,
        "3 Stars": 7,
        "4 Stars": 26,
        "5 Stars": 60,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/motorola-43-inch-tv-1065x800-1571741963.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Motorola",
        "Product Name": "Motorola 43 Inches Full HD TV (43SAFHDM, Black)",
        "Model": "43 Inch Full HD TV",
        "Model Name": "43SAFHDM",
        "Price": "â‚¹ 24,999",
        "TotalRating": 1211,
        "1 Stars": 12,
        "2 Stars": 5,
        "3 Stars": 9,
        "4 Stars": 22,
        "5 Stars": 52,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153758_832_blaupunkt_32-inch-led-hd-ready-tv-bla32as460.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Blaupunkt",
        "Product Name": "Blaupunkt 32 Inches HD Ready LED Smart TV (BLA32AS460)",
        "Model": "32 Inch LED HD Ready TV (BLA32AS460)",
        "Model Name": "BLA32AS460",
        "Price": "â‚¹ 14,999",
        "TotalRating": 962,
        "1 Stars": 9,
        "2 Stars": 2,
        "3 Stars": 4,
        "4 Stars": 19,
        "5 Stars": 65,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153750_832_intex_32-inch-led-hd-ready-tv-avoir-32smart-splash-plus.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Intex",
        "Product Name": "Intex 32 Inches HD Ready LED Smart TV (AVOIR 32SMART SPLASH PLUS, Black)",
        "Model": "32 Inch LED HD Ready TV (AVOIR 32SMART SPLASH PLUS)",
        "Model Name": "AVOIR 32SMART SPLASH PLUS",
        "Price": "â‚¹ 9,999",
        "TotalRating": 796,
        "1 Stars": 7,
        "2 Stars": 4,
        "3 Stars": 9,
        "4 Stars": 31,
        "5 Stars": 50,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/motorola-32-inch-tv-1070x800-1571744830.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Motorola",
        "Product Name": "Motorola 32 Inches HD TV (32SAFHDM, Black)",
        "Model": "32 Inch HD TV",
        "Model Name": "32SAFHDM",
        "Price": "â‚¹ 14,499",
        "TotalRating": 53,
        "1 Stars": 8,
        "2 Stars": 2,
        "3 Stars": 2,
        "4 Stars": 26,
        "5 Stars": 62,

        "About": "Black | Smart tv - no"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153764_832_blaupunkt_49-inch-led-ultra-hd-tv-bla49au680.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Blaupunkt",
        "Product Name": "Blaupunkt 49 Inches Ultra HD LED Smart TV (BLA49AU680)",
        "Model": "49 Inch LED Ultra HD TV (BLA49AU680)",
        "Model Name": "BLA49AU680",
        "Price": "â‚¹ 28,999",
        "TotalRating": 48,
        "1 Stars": 6,
        "2 Stars": 2,
        "3 Stars": 2,
        "4 Stars": 15,
        "5 Stars": 75,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153613_832_vu_55-inch-led-ultra-hd-4k-tv-55su134.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Vu",
        "Product Name": "Vu 55 Inches Ultra HD (4K) LED Smart TV (55SU134, Black)",
        "Model": "55 Inch LED Ultra HD (4K) TV (55SU134)",
        "Model Name": "55SU134",
        "Price": "â‚¹ 44,999",
        "TotalRating": 547,
        "1 Stars": 11,
        "2 Stars": 5,
        "3 Stars": 7,
        "4 Stars": 20,
        "5 Stars": 57,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153776_832_cloudwalker_32-inch-led-hd-ready-tv-cloud-32sh.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "CloudWalker",
        "Product Name": "CloudWalker CloudTV 80cm (32 inch) HD Ready LED Smart TV(CLOUD TV32SH)",
        "Model": "32 Inch LED HD Ready TV (CLOUD 32SH)",
        "Model Name": "CLOUD 32SH",
        "Price": "â‚¹ 13,499",
        "TotalRating": 992,
        "1 Stars": 10,
        "2 Stars": 2,
        "3 Stars": 10,
        "4 Stars": 25,
        "5 Stars": 53,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548153700_832_iffalcon_75-inch-led-ultra-hd-tv-75h2a.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "iFFalcon",
        "Product Name": "Iffalcon 75 Inches Ultra HD LED Smart TV (75H2A)",
        "Model": "75 Inch LED Ultra HD TV (75H2A)",
        "Model Name": "75H2A",
        "Price": "â‚¹ 149,999",
        "TotalRating": 21,
        "1 Stars": 29,
        "2 Stars": 10,
        "3 Stars": 0,
        "4 Stars": 19,
        "5 Stars": 43,

        "About": "silver | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548154386_832_nacson_32-inch-led-hd-ready-tv-ns32w80.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Nacson",
        "Product Name": "Nacson 32 Inches HD Ready LED Smart TV (NS32W80, Black)",
        "Model": "32 Inch LED HD Ready TV (NS32W80)",
        "Model Name": "NS32W80",
        "Price": "â‚¹ 13,990",
        "TotalRating": 7,
        "1 Stars": 0,
        "2 Stars": 0,
        "3 Stars": 14,
        "4 Stars": 43,
        "5 Stars": 43,

        "About": "Black | Smart tv - no"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548152957_832_iffalcon_32-inch-led-hd-ready-tv-32f2a.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "iFFalcon",
        "Product Name": "Iffalcon 32 Inches HD Ready LED Smart TV (32F2A)",
        "Model": "32 Inch LED HD Ready TV (32F2A)",
        "Model Name": "32F2A",
        "Price": "â‚¹ 12,499",
        "TotalRating": 1219,
        "1 Stars": 6,
        "2 Stars": 3,
        "3 Stars": 6,
        "4 Stars": 25,
        "5 Stars": 60,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/large/coocaa-55s3g-55s3g-original-imafpvkhddzgyfph-416x261-1584705436.jpeg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Coocaa",
        "Product Name": "Coocaa 55 Inches Ultra HD (4K) LED Smart TV (55S3G, Black)",
        "Model": "55 Inch LED Ultra HD (4K) TV (55S3G)",
        "Model Name": "55S3G",
        "Price": "â‚¹ 31,999",
        "TotalRating": 71,
        "1 Stars": 1,
        "2 Stars": 1,
        "3 Stars": 6,
        "4 Stars": 18,
        "5 Stars": 73,

        "About": "Black | Smart tv - yes"
    },
    {
        "Image": "https://i.gadgets360cdn.com/products/televisions/large/1548155066_832_onida_58-inch-led-ultra-hd-4k-tv-58uic.jpg?downsize=*:180&amp;output-quality=80&amp;output-format=webp",
        "Brand": "Onida",
        "Product Name": "Onida 58 Inches Ultra HD LED Smart TV (58UIC)",
        "Model": "58 Inch LED Ultra HD (4K) TV (58UIC)",
        "Model Name": "58UIC",
        "Price": "â‚¹ 49,999",
        "TotalRating": 0,
        "1 Stars": 0,
        "2 Stars": 0,
        "3 Stars": 0,
        "4 Stars": 0,
        "5 Stars": 0,

        "About": "Silver | Smart tv - no"
    }
];